### ISSUE TITLE
Issue with variables

### ISSUE THREAD

**Issue by avanes** [antyakushev/postcss-default-unit#3]
Please check: I used postcss-simple-vars, and got this:

`background: $orange;` -> `background: #ec9214px;`

**Comment by antyakushev** [comment]
Try putting postcss-default-unit after postcss-simple-vars. In PostCSS plugin order is important, it seems I have to mention this in the read me.

**Comment by avanes** [comment]
Yes, it's in very end of plugins, but still buggy :\

**Comment by antyakushev** [comment]
Yeah, it turned out to have nothing to do with postcss-simple-vars. Thanks for the bug :smile:
